ALTER TABLE booking MODIFY booking_status ENUM('SCHEDULED','ARRIVED','DELAYED','CANCELLED','ASSIGNING_DRIVER','IN_RIDE','COMPLETED');
ALTER TABLE car MODIFY brand ENUM('MAHINDRA','TATA','MARUTI_SIZUKI','HYUNDIA','KIA','TOYOTA','FORD','SKODA','NISSAN');
ALTER TABLE driver MODIFY driver_approval_status ENUM('APPROVED','PENDING','REJECTED','IN_PROGRESS');

ALTER TABLE driver ADD CONSTRAINT check_rating CHECK(driver.rating >=0 AND driver.rating<=5);