ALTER TABLE booking
DROP FOREIGN KEY FK_BOOKING_ON_PASSENGER;

ALTER TABLE passenger
MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE booking
ADD CONSTRAINT FK_BOOKING_ON_PASSENGER
FOREIGN KEY (passenger_id) REFERENCES passenger(id);